# Autogenerated wrapper script for ELFIO_jll for any
export elfio_hpp

JLLWrappers.@generate_wrapper_header("ELFIO")
JLLWrappers.@declare_file_product(elfio_hpp)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        elfio_hpp,
        "include/elfio/elfio.hpp",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
